name: "Dynamic Application Security Testing (DAST) with Nuclei"
description: "Nuclei is an open-source web application security scanner developed by ProjectDiscovery.io."
branding:
  icon: "alert-circle"
  color: "purple"

inputs:
  urls-txt:
    description: "List of urls to run templates"
    required: true
    default: "nuclei.txt"
  custom-templates:
    description: "Custom templates to check on urls"
    required: false
    default: "custom-templates/"
  user-agent:
    description: "Set User-Agent header"
    required: false
    default: "Nuclei - Open-source project (github.com/projectdiscovery/nuclei)"
  slack-token:
    description: "Authentication token bearing required scopes"
    required: false
    default: ""
  slack-channel:
    description: "Channel, private group, or IM channel to send message to. Can be an encoded ID, or a name"
    required: false
    default: ""
  dd-api-key:
    description: "An API key is required by the Datadog Agent to submit metrics and events to Datadog"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - run: |
        git clone https://github.com/projectdiscovery/nuclei.git
        cd nuclei/cmd/nuclei/
        go build
        echo "::add-path::${{ github.workspace }}/nuclei/cmd/nuclei/"
      shell: bash

    - run: |
        nuclei -l ${{ inputs.urls-txt }} \
          -json \
          -silent \
          -update-directory ${{ github.workspace }} \
          -update-templates \
          -t nuclei-templates/ \
          -t ${{ inputs.custom-templates }} \
          -H "User-Agent:${{ inputs.user-agent }}" \
          -o nuclei.log
      shell: bash
